# Specify a base image
FROM node:alpine


WORKDIR '/app'

#Utilizando docker-compose no haría falta utilizar las instrucciones COPY pero si un día dejasemos de utilizarlo nos harían falta, no es problema dejarlo así.

# install some dependencies
COPY package.json .
RUN npm install


COPY . .

# Default command
CMD ["npm", "run", "start"]

